### ISSUE TITLE
Classifier service recommend -> parent tag filter

### ISSUE THREAD

**Issue by petermezei** [slamby/slamby-api#14]
Built-in classifier service recommend filter option. Filter by tags during the recommendation

**Comment by attilalaszlo** [comment]
what do you mean: skipping tags, skipping tags by name?
Is it neccessary?

**Comment by petermezei** [comment]
usecase for "other" categories. My idea was a name based filter.

**Comment by attilalaszlo** [comment]
but for every recommend request?
IMO it's a typival case for the Activate settings

**Comment by petermezei** [comment]
ok, agree.
