### ISSUE TITLE
concurrent requests limit - research

### ISSUE THREAD

**Issue by petermezei** [slamby/slamby-api#26]
Basic research about max connection number. What happen when 1000 requests hit the API server? Any settings?

**Comment by attilalaszlo** [comment]
https://github.com/stefanprodan/WebApiThrottle

it can be a solution

**Comment by attilalaszlo** [comment]
The AspNetCoreRateLimit library is not the best choice for us right now. It's rather for real throttle limiting, e.g.: for a centralized API with multi separate clients. Then you can limit the request number for each clients. But with this library we can't limit the concurrent requests (which is now our main prio in this issue)

**Comment by attilalaszlo** [comment]
I will try https://github.com/lvermeulen/LimitsMiddleware.aspnetcore 
this is a aspnetcore ported version of this library:
https://github.com/damianh/LimitsMiddleware
