### ISSUE TITLE
delete processes?

### ISSUE THREAD

**Issue by attilalaszlo** [slamby/slamby-api#3]
A user can have hundreds or thousands of processes, after a time. And can be a big (and slow) response if you want to get all.
Maybe a "delete all processes" endpoint can be useful.

**Comment by petermezei** [comment]
Yes, I support it. Or move to the bin option, hiding the elements ,but does not remove them. Just an idea.

**Comment by attilalaszlo** [comment]
or even with the `allStatus=true` parameter, only response the processes within the last 30 days.
And a plus integer parameter: `lastDays=30` if you want to get back from last X days

**Comment by petermezei** [comment]
allStatus time limitation and lastDays parameter sounds great. In other solutions the time filter is similiar in terms of naming convention? lastDays filter is usuall?

**Comment by attilalaszlo** [comment]
Hmm..maybe just make an allTime parameter which is a boolean. And if it's false (default) then the API will response the processes from the last 30 days, otherwise with all of the processes
