### ISSUE TITLE
Storage capacity check

### ISSUE THREAD

**Issue by attilalaszlo** [slamby/slamby-api#6]
Make a middleware or action filter, if the HDD do not have enough capacity then some of the request (document add, document bulk add, tag add, service prepare... etc) should return with a human readable error message.

**Comment by attilalaszlo** [comment]
The capacity minimum must be big enough for the nginx too. It can cause:
```
Failed 28: No Space Left on Device
```

**Comment by petermezei** [comment]
@attilalaszlo it would be useful to put resource warnings into Insight, as a toaster + noti. Any idea?

**Comment by attilalaszlo** [comment]
The status endpoint should give back not just the free space but the total space also

**Comment by attilalaszlo** [comment]
@ 4dc4135

**Comment by attilalaszlo** [comment]
6e48d90
